spring.application.name=AssetFlow
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/db_assetflow?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=abc123

# Hibernate / JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect